DROP DATABASE IF EXISTS hsrtracker;
CREATE DATABASE hsrtracker;
USE hsrtracker;
DROP USER IF EXISTS hsrt;
CREATE USER 'hsrt'@'%' IDENTIFIED BY 'HSRTracker2021';
GRANT INSERT, DELETE, UPDATE, SELECT ON hsrtracker.* TO 'hsrt'@'%';

CREATE TABLE active_clients (`passkey` CHAR(16) NOT NULL, `peer_id` CHAR(32) NOT NULL, `info_hash` CHAR(40) NOT NULL, `ip` VARCHAR(256) NOT NULL, `port` SMALLINT UNSIGNED NOT NULL, `left` BIGINT UNSIGNED NOT NULL, `_hashval` CHAR(32) NOT NULL, PRIMARY KEY (`_hashval`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE torrents (`info_hash` CHAR(40) NOT NULL, `category` TINYINT NOT NULL, `title` VARCHAR(1024) NOT NULL, `dateUploaded` DATETIME NOT NULL, `size` BIGINT UNSIGNED NOT NULL, `seeders` MEDIUMINT UNSIGNED NOT NULL, `leechers` MEDIUMINT UNSIGNED NOT NULL, `completes` MEDIUMINT UNSIGNED NOT NULL, `uploader` MEDIUMINT NOT NULL, `_hashval` CHAR(32) NOT NULL, PRIMARY KEY (`_hashval`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;